# Generated by Django 4.0.6 on 2022-08-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='metadata_csv',
            field=models.FileField(blank=True, null=True, upload_to='metadata_csv'),
        ),
        migrations.AlterField(
            model_name='files',
            name='metadata_txt',
            field=models.FileField(blank=True, null=True, upload_to='metadata_txt'),
        ),
    ]
