# Generated by Django 4.0.6 on 2022-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_files_metadata_csv_alter_files_metadata_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='metadata_csv',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
