# Generated by Django 4.0.6 on 2022-08-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_files_metadata_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='metadata_csv',
        ),
        migrations.AlterField(
            model_name='files',
            name='metadata_txt',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
