# Generated by Django 4.0.6 on 2022-08-06 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_files_metadata_csv_alter_files_metadata_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='extracted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
