# Generated by Django 4.0.6 on 2022-08-08 15:54

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='document_to_extract'),
        ),
    ]
