# Generated by Django 4.0.6 on 2022-08-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_files_file_type_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_type',
        ),
    ]
